-- ============================================================================
-- SQL Portfolio Project: Marketing Attribution & Campaign Analytics
-- File: analysis_queries.sql
-- Description: 37 professional SQL analysis queries organized into 7 sections
--              to extract business-critical insights from campaign data.
-- ============================================================================

-- ============================================================================
-- SECTION 1 – Basic Analysis
-- ============================================================================

-- Query 1: Total Revenue
-- Purpose: Evaluates the total gross revenue generated across all campaigns.
SELECT SUM(revenue) AS total_revenue 
FROM marketing_campaigns;

-- Query 2: Total Acquisition Cost
-- Purpose: Evaluates the total marketing acquisition spend across all campaigns.
SELECT SUM(acquisition_cost) AS total_acquisition_cost 
FROM marketing_campaigns;

-- Query 3: Total Clicks
-- Purpose: Calculates the aggregate clicks generated to measure audience response.
SELECT SUM(clicks) AS total_clicks 
FROM marketing_campaigns;

-- Query 4: Total Leads
-- Purpose: Calculates the total lead generation count across all funnels.
SELECT SUM(leads) AS total_leads 
FROM marketing_campaigns;

-- Query 5: Total Conversions
-- Purpose: Measures total buyer conversions completed, reflecting campaign success.
SELECT SUM(conversions) AS total_conversions 
FROM marketing_campaigns;

-- Query 6: Average ROI
-- Purpose: Computes average campaign return on investment (expressed as a ratio/multiplier).
SELECT AVG(roi) AS average_roi 
FROM marketing_campaigns;

-- Query 7: Average CTR (Click-Through Rate)
-- Purpose: Evaluates top-funnel creative efficiency by checking average CTR.
SELECT AVG(ctr) AS average_ctr 
FROM marketing_campaigns;

-- Query 8: Average Conversion Rate
-- Purpose: Measures bottom-funnel landing page efficiency by checking click-to-buy rates.
SELECT AVG(conversion_rate) AS average_conversion_rate 
FROM marketing_campaigns;


-- ============================================================================
-- SECTION 2 – Brand Analysis
-- ============================================================================

-- Query 9: Revenue by Brand
-- Purpose: Summarizes gross revenue generated by each brand (Nykaa, Purplle, Tira).
SELECT brand, 
       SUM(revenue) AS total_revenue
FROM marketing_campaigns
GROUP BY brand
ORDER BY total_revenue DESC;

-- Query 10: ROI by Brand
-- Purpose: Compares average campaign return on investment across brands.
SELECT brand, 
       AVG(roi) AS average_roi
FROM marketing_campaigns
GROUP BY brand
ORDER BY average_roi DESC;

-- Query 11: CTR by Brand
-- Purpose: Compares average audience click-through rate across brands.
SELECT brand, 
       AVG(ctr) AS average_ctr
FROM marketing_campaigns
GROUP BY brand
ORDER BY average_ctr DESC;

-- Query 12: CPA (Cost Per Acquisition) by Brand
-- Purpose: Checks cost efficiency of conversions for each brand. Lower is better.
SELECT brand, 
       AVG(cpa) AS average_cpa
FROM marketing_campaigns
GROUP BY brand
ORDER BY average_cpa ASC;

-- Query 13: Rank Brands by Revenue (Dense Rank)
-- Purpose: Applies DENSE_RANK() to rank brands based on total revenue generated.
SELECT brand,
       SUM(revenue) AS total_revenue,
       DENSE_RANK() OVER (ORDER BY SUM(revenue) DESC) AS brand_revenue_rank
FROM marketing_campaigns
GROUP BY brand;


-- ============================================================================
-- SECTION 3 – Channel Analysis
-- ============================================================================

-- Query 14: Revenue by Channel
-- Purpose: Groups campaigns by channel configurations to find the top revenue drivers.
SELECT channel_used, 
       SUM(revenue) AS total_revenue
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY total_revenue DESC;

-- Query 15: ROI by Channel
-- Purpose: Determines the channels yielding the highest return on investment ratios.
SELECT channel_used, 
       AVG(roi) AS average_roi
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY average_roi DESC;

-- Query 16: Top 10 Channels by Conversions
-- Purpose: Identifies the top 10 channels that drove the largest conversion volumes.
SELECT channel_used, 
       SUM(conversions) AS total_conversions
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY total_conversions DESC
LIMIT 10;

-- Query 17: Lowest Performing Channels by ROI (Bottom 10)
-- Purpose: Uncovers the bottom 10 underperforming channels based on average ROI.
SELECT channel_used, 
       AVG(roi) AS average_roi
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY average_roi ASC
LIMIT 10;

-- Query 18: Average CPC (Cost Per Click) by Channel
-- Purpose: Audits cost-per-click efficiency across various marketing channel configurations.
SELECT channel_used, 
       AVG(cpc) AS average_cpc
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY average_cpc ASC;

-- Query 19: Average CPA (Cost Per Acquisition) by Channel
-- Purpose: Audits average customer acquisition cost across channels.
SELECT channel_used, 
       AVG(cpa) AS average_cpa
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY average_cpa ASC;


-- ============================================================================
-- SECTION 4 – Campaign Analysis
-- ============================================================================

-- Query 20: Campaign Type Performance
-- Purpose: Evaluates core campaign strategies (Paid Ads, Social Media, Email, SEO, Influencer)
--          by revenue, ROI, CTR, Conversion Rate, and CPA.
SELECT campaign_type,
       SUM(revenue) AS total_revenue,
       AVG(roi) AS average_roi,
       AVG(ctr) AS average_ctr,
       AVG(conversion_rate) AS average_conversion_rate,
       AVG(cpa) AS average_cpa
FROM marketing_campaigns
GROUP BY campaign_type
ORDER BY total_revenue DESC;

-- Query 21: Top 10 Campaigns by Revenue
-- Purpose: Pinpoints individual high-performing campaigns to study creative formats.
SELECT campaign_id, 
       brand, 
       campaign_type, 
       revenue
FROM marketing_campaigns
ORDER BY revenue DESC
LIMIT 10;

-- Query 22: Bottom 10 Campaigns by ROI
-- Purpose: Identifies campaigns with the lowest ROI (uncovering critical net-loss runs).
SELECT campaign_id, 
       brand, 
       campaign_type, 
       roi,
       revenue,
       acquisition_cost
FROM marketing_campaigns
ORDER BY roi ASC
LIMIT 10;

-- Query 23: Campaign Duration Analysis
-- Purpose: Analyzes performance metrics by campaign duration buckets (Short, Medium, Long).
SELECT CASE 
           WHEN duration <= 10 THEN 'Short (<= 10 Days)'
           WHEN duration <= 20 THEN 'Medium (11-20 Days)'
           ELSE 'Long (> 20 Days)'
       END AS duration_bucket,
       COUNT(*) AS campaign_count,
       SUM(revenue) AS total_revenue,
       AVG(roi) AS average_roi,
       AVG(ctr) AS average_ctr,
       AVG(conversion_rate) AS average_conversion_rate
FROM marketing_campaigns
GROUP BY 1
ORDER BY average_roi DESC;


-- ============================================================================
-- SECTION 5 – Customer Analysis
-- ============================================================================

-- Query 24: Customer Segment Performance
-- Purpose: Evaluates customer segment value based on revenue, conversions, CTR, and ROI.
SELECT customer_segment,
       SUM(revenue) AS total_revenue,
       SUM(conversions) AS total_conversions,
       AVG(ctr) AS average_ctr,
       AVG(roi) AS average_roi,
       SUM(acquisition_cost) AS total_acquisition_cost
FROM marketing_campaigns
GROUP BY customer_segment
ORDER BY total_revenue DESC;

-- Query 25: Language Analysis
-- Purpose: Examines localization performance by grouping metrics by campaign language.
SELECT language,
       SUM(revenue) AS total_revenue,
       SUM(conversions) AS total_conversions,
       AVG(roi) AS average_roi,
       AVG(ctr) AS average_ctr
FROM marketing_campaigns
GROUP BY language
ORDER BY total_revenue DESC;

-- Query 26: Monthly Revenue Trend
-- Purpose: Group revenue chronologically to identify seasonality (PostgreSQL syntax).
-- Note: For MySQL, replace DATE_TRUNC('month', date) with DATE_FORMAT(date, '%Y-%m-01').
SELECT DATE_TRUNC('month', date) AS campaign_month,
       SUM(revenue) AS total_revenue
FROM marketing_campaigns
GROUP BY campaign_month
ORDER BY campaign_month ASC;

-- Query 27: Monthly ROI Trend
-- Purpose: Group ROI chronologically to identify seasonal efficiency variations.
SELECT DATE_TRUNC('month', date) AS campaign_month,
       AVG(roi) AS average_roi
FROM marketing_campaigns
GROUP BY campaign_month
ORDER BY campaign_month ASC;


-- ============================================================================
-- SECTION 6 – Advanced SQL (Window Functions & Views)
-- ============================================================================

-- Query 28: Brand Cumulative Running Total Revenue
-- Purpose: Computes the cumulative running total of revenue for each brand chronologically.
--          Utilizes CTEs and window partition functions.
WITH DailyBrandRevenue AS (
    SELECT brand, 
           date, 
           SUM(revenue) AS daily_revenue
    FROM marketing_campaigns
    GROUP BY brand, date
)
SELECT brand, 
       date, 
       daily_revenue,
       SUM(daily_revenue) OVER (
           PARTITION BY brand 
           ORDER BY date 
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
       ) AS running_total_revenue
FROM DailyBrandRevenue
ORDER BY brand, date;

-- Query 29: Brand 7-Day Moving Average of Campaign ROI
-- Purpose: Computes the 7-day trailing moving average of campaign ROI by brand.
--          Helps smooth out daily variations to track trends.
WITH DailyBrandROI AS (
    SELECT brand, 
           date, 
           AVG(roi) AS daily_avg_roi
    FROM marketing_campaigns
    GROUP BY brand, date
)
SELECT brand, 
       date, 
       daily_avg_roi,
       AVG(daily_avg_roi) OVER (
           PARTITION BY brand 
           ORDER BY date 
           ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
       ) AS moving_avg_roi_7day
FROM DailyBrandROI
ORDER BY brand, date;

-- Query 30: Campaign Performance Analytical View
-- Purpose: Creates a reporting view that partitions monthly brand performance
--          and implements ROW_NUMBER(), RANK(), DENSE_RANK(), LAG(), and LEAD() 
--          to calculate month-over-month differences.
CREATE OR REPLACE VIEW view_brand_monthly_rankings AS
WITH BrandMonthlyPerformance AS (
    SELECT brand, 
           DATE_TRUNC('month', date) AS campaign_month,
           SUM(revenue) AS total_revenue,
           AVG(roi) AS avg_roi
    FROM marketing_campaigns
    GROUP BY brand, campaign_month
)
SELECT brand, 
       campaign_month, 
       total_revenue,
       
       -- Row numbering for ordering
       ROW_NUMBER() OVER (
           PARTITION BY brand 
           ORDER BY total_revenue DESC
       ) AS revenue_row_num,
       
       -- Ranking within each month
       RANK() OVER (
           PARTITION BY campaign_month 
           ORDER BY total_revenue DESC
       ) AS monthly_revenue_rank,
       
       -- Dense Ranking within each month
       DENSE_RANK() OVER (
           PARTITION BY campaign_month 
           ORDER BY total_revenue DESC
       ) AS monthly_revenue_dense_rank,
       
       -- Lagging metric: Prior month's revenue to calculate growth
       LAG(total_revenue, 1) OVER (
           PARTITION BY brand 
           ORDER BY campaign_month
       ) AS prior_month_revenue,
       
       -- Leading metric: Next month's revenue for forecast checks
       LEAD(total_revenue, 1) OVER (
           PARTITION BY brand 
           ORDER BY campaign_month
       ) AS next_month_revenue
FROM BrandMonthlyPerformance;

-- Query to select from view:
-- SELECT * FROM view_brand_monthly_rankings;


-- ============================================================================
-- SECTION 7 – Business Queries
-- ============================================================================

-- Query 31: Highest Revenue Campaign
-- Purpose: Pinpoints the single most successful campaign by gross revenue.
SELECT campaign_id, 
       brand, 
       campaign_type, 
       revenue
FROM marketing_campaigns
ORDER BY revenue DESC
LIMIT 1;

-- Query 32: Lowest CPA Campaign (Min conversions > 0)
-- Purpose: Finds the single most cost-effective campaign that achieved conversions.
SELECT campaign_id, 
       brand, 
       campaign_type, 
       cpa,
       conversions
FROM marketing_campaigns
WHERE conversions > 0
ORDER BY cpa ASC
LIMIT 1;

-- Query 33: Highest ROI Campaign
-- Purpose: Identifies the campaign that achieved the highest percentage multiplier return.
SELECT campaign_id, 
       brand, 
       campaign_type, 
       roi,
       revenue,
       acquisition_cost
FROM marketing_campaigns
ORDER BY roi DESC
LIMIT 1;

-- Query 34: Worst ROI Campaign (Net Loss Campaign)
-- Purpose: Identifies the campaign with the lowest (most negative) ROI.
SELECT campaign_id, 
       brand, 
       campaign_type, 
       roi,
       revenue,
       acquisition_cost
FROM marketing_campaigns
ORDER BY roi ASC
LIMIT 1;

-- Query 35: Top Performing Month
-- Purpose: Identifies the single calendar month that generated the highest total revenue.
SELECT DATE_TRUNC('month', date) AS campaign_month,
       SUM(revenue) AS total_revenue
FROM marketing_campaigns
GROUP BY campaign_month
ORDER BY total_revenue DESC
LIMIT 1;

-- Query 36: Highest Converting Channel
-- Purpose: Identifies the channel configuration that generated the maximum total conversions.
SELECT channel_used,
       SUM(conversions) AS total_conversions
FROM marketing_campaigns
GROUP BY channel_used
ORDER BY total_conversions DESC
LIMIT 1;

-- Query 37: Most Efficient Brand
-- Purpose: Identifies the brand portfolio with the lowest average Cost Per Acquisition (CPA).
SELECT brand,
       AVG(cpa) AS average_cpa
FROM marketing_campaigns
GROUP BY brand
ORDER BY average_cpa ASC
LIMIT 1;


-- ============================================================================
-- SECTION 8 – Advanced Analytical Queries (PostgreSQL Specific)
-- ============================================================================

-- Query 38: Percentile Analysis of Campaign Revenue
-- Purpose: Finds the 90th percentile of campaign revenue to define benchmark thresholds.
SELECT percentile_cont(0.9) WITHIN GROUP (ORDER BY revenue) AS revenue_90th_percentile
FROM marketing_campaigns;

-- Query 39: ROI Decile Classification (NTILE())
-- Purpose: Divides all campaigns into 10 groups (deciles) based on ROI.
SELECT campaign_id, 
       brand, 
       roi,
       NTILE(10) OVER (ORDER BY roi DESC) AS roi_decile
FROM marketing_campaigns;

-- Query 40: Revenue Contribution Percentage within Brand (Window Partition)
-- Purpose: Calculates what percentage of brand revenue was driven by each campaign.
SELECT campaign_id, 
       brand, 
       revenue,
       (revenue / SUM(revenue) OVER (PARTITION BY brand)) * 100.0 AS brand_revenue_contribution_pct
FROM marketing_campaigns
ORDER BY brand, brand_revenue_contribution_pct DESC;

-- Query 41: Top 20% Campaigns by Revenue (Window Function Filter)
-- Purpose: Identifies the top-tier 20% revenue-generating campaigns.
WITH RankedCampaigns AS (
    SELECT campaign_id, 
           brand, 
           revenue,
           PERCENT_RANK() OVER (ORDER BY revenue DESC) AS revenue_percent_rank
    FROM marketing_campaigns
)
SELECT campaign_id, 
       brand, 
       revenue
FROM RankedCampaigns
WHERE revenue_percent_rank <= 0.20
ORDER BY revenue DESC;

-- Query 42: Brand Market Share Analysis
-- Purpose: Computes market share percentage of each brand based on overall revenue.
SELECT brand,
       SUM(revenue) AS brand_revenue,
       (SUM(revenue) / SUM(SUM(revenue)) OVER ()) * 100.0 AS market_share_percentage
FROM marketing_campaigns
GROUP BY brand
ORDER BY market_share_percentage DESC;

-- Query 43: Channel Market Share within Each Brand
-- Purpose: Calculates how revenue is distributed across channel groups for each brand portfolio.
WITH BrandChannelRevenue AS (
    SELECT brand, 
           channel_used, 
           SUM(revenue) AS channel_revenue
    FROM marketing_campaigns
    GROUP BY brand, channel_used
)
SELECT brand, 
       channel_used, 
       channel_revenue,
       (channel_revenue / SUM(channel_revenue) OVER (PARTITION BY brand)) * 100.0 AS channel_brand_revenue_pct
FROM BrandChannelRevenue
ORDER BY brand, channel_brand_revenue_pct DESC;

-- Query 44: Month-over-Month Revenue Growth Percentage
-- Purpose: Computes month-over-month gross revenue growth rates.
WITH MonthlyRevenue AS (
    SELECT DATE_TRUNC('month', date) AS campaign_month,
           SUM(revenue) AS current_revenue
    FROM marketing_campaigns
    GROUP BY campaign_month
)
SELECT campaign_month,
       current_revenue,
       LAG(current_revenue, 1) OVER (ORDER BY campaign_month) AS prior_revenue,
       ((current_revenue - LAG(current_revenue, 1) OVER (ORDER BY campaign_month)) / 
        LAG(current_revenue, 1) OVER (ORDER BY campaign_month)) * 100.0 AS mom_growth_percentage
FROM MonthlyRevenue
ORDER BY campaign_month;

-- Query 45: Campaign Bounded Rankings within Brand Portfolios (Top 5 per Brand)
-- Purpose: Ranks campaigns by revenue within their brands and displays the top 5 per brand.
WITH RankedBrandCampaigns AS (
    SELECT campaign_id, 
           brand, 
           revenue,
           DENSE_RANK() OVER (PARTITION BY brand ORDER BY revenue DESC) AS brand_rank
    FROM marketing_campaigns
)
SELECT campaign_id, 
       brand, 
       revenue, 
       brand_rank
FROM RankedBrandCampaigns
WHERE brand_rank <= 5
ORDER BY brand, brand_rank;

-- Query 46: Highest Month-over-Month Revenue Growth Month
-- Purpose: Pinpoints the calendar month that achieved the largest positive revenue growth rate.
WITH MonthlyGrowth AS (
    SELECT DATE_TRUNC('month', date) AS campaign_month,
           SUM(revenue) AS current_revenue,
           LAG(SUM(revenue), 1) OVER (ORDER BY DATE_TRUNC('month', date)) AS prior_revenue
    FROM marketing_campaigns
    GROUP BY DATE_TRUNC('month', date)
)
SELECT campaign_month,
       current_revenue,
       prior_revenue,
       ((current_revenue - prior_revenue) / prior_revenue) * 100.0 AS growth_rate_pct
FROM MonthlyGrowth
WHERE prior_revenue IS NOT NULL
ORDER BY growth_rate_pct DESC
LIMIT 1;

-- Query 47: Rolling 30-Day Cumulative Revenue (Moving Total)
-- Purpose: Calculates a trailing 30-day cumulative revenue sum chronologically.
WITH DailyRevenue AS (
    SELECT date, 
           SUM(revenue) AS daily_revenue
    FROM marketing_campaigns
    GROUP BY date
)
SELECT date, 
       daily_revenue,
       SUM(daily_revenue) OVER (
           ORDER BY date 
           RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
       ) AS rolling_30day_revenue
FROM DailyRevenue
ORDER BY date;

